const WORD_PAIRS = [

  // ── Food & Drink ──────────────────────────────────────
  { word: "Momo", hint: "Steamed" },
  { word: "Dal Bhat", hint: "Daily" },
  { word: "Thukpa", hint: "Noodle Soup" },
  { word: "Chatamari", hint: "Newari" },
  { word: "Sel Roti", hint: "Festival" },
  { word: "Chowmein", hint: "Fried" },
  { word: "Samosa", hint: "Crispy" },
  { word: "Lassi", hint: "Yogurt" },
  { word: "Chiya", hint: "Morning" },
  { word: "Achar", hint: "Spicy" },
  { word: "Dhindo", hint: "Thick" },
  { word: "Sukuti", hint: "Dried Meat" },
  { word: "Wai Wai", hint: "Packet" },
  { word: "Juju Dhau", hint: "Bhaktapur" },
  { word: "Tongba", hint: "Millet" },
  { word: "Kheer", hint: "Sweet Rice" },
  { word: "Pani Puri", hint: "Hollow" },
  { word: "Sekuwa", hint: "Grilled" },
  { word: "Yomari", hint: "Newari Sweet" },
  { word: "Raksi", hint: "Homemade" },

  // ── Places in Nepal ───────────────────────────────────
  { word: "Mt Everest", hint: "Tallest" },
  { word: "Pashupatinath", hint: "Temple" },
  { word: "Boudhanath", hint: "Stupa" },
  { word: "Pokhara", hint: "Lakeside" },
  { word: "Thamel", hint: "Tourist" },
  { word: "Lumbini", hint: "Buddha" },
  { word: "Chitwan", hint: "Jungle" },
  { word: "Annapurna", hint: "Trek" },
  { word: "Mustang", hint: "Desert" },
  { word: "Bhaktapur", hint: "Old City" },
  { word: "Patan", hint: "Durbar" },
  { word: "Swayambhunath", hint: "Monkey Temple" },
  { word: "Rara Lake", hint: "Remote" },
  { word: "Langtang", hint: "Valley" },
  { word: "Birgunj", hint: "Border" },

  // ── Nepali Culture & Things ───────────────────────────
  { word: "Dashain", hint: "Tika" },
  { word: "Tihar", hint: "Lights" },
  { word: "Holi", hint: "Colors" },
  { word: "Kumari", hint: "Living Goddess" },
  { word: "Khukuri", hint: "Blade" },
  { word: "Dhaka Fabric", hint: "Woven" },
  { word: "Dhol", hint: "Drum" },
  { word: "Sarangi", hint: "String" },
  { word: "Topi", hint: "Hat" },
  { word: "Daura Suruwal", hint: "National Dress" },
  { word: "Rudraksha", hint: "Beads" },
  { word: "Thangka", hint: "Painting" },
  { word: "Load Shedding", hint: "Darkness" },
  { word: "Bandha", hint: "Strike" },
  { word: "Tempo", hint: "Three Wheeler" },
  { word: "Microbus", hint: "Crowded" },
  { word: "Sajha Bus", hint: "Green" },
  { word: "Routine of Nepal Banda", hint: "News" },
  // ── Famous Nepali People ──────────────────────────────
  { word: "Prithvi Narayan Shah", hint: "Unifier" },
  { word: "Tenzing Norgay", hint: "Summit" },
  { word: "BP Koirala", hint: "Democracy" },
  { word: "Pasang Lhamu", hint: "Climber" },
  { word: "Arniko", hint: "Pagoda" },
  { word: "Narayan Gopal", hint: "Melody" },
  { word: "Parbat Sah", hint: "Comedy" },

  // ── Global Celebrities (Nepal-familiar) ──────────────
  { word: "Cristiano Ronaldo", hint: "Freekick" },
  { word: "Lionel Messi", hint: "Dribble" },
  { word: "Shah Rukh Khan", hint: "Bollywood" },
  { word: "Salman Khan", hint: "Bhai" },
  { word: "Deepika Padukone", hint: "Actress" },
  { word: "Amitabh Bachchan", hint: "Legend" },
  { word: "Taylor Swift", hint: "Eras Tour" },
  { word: "BTS", hint: "K-pop" },
  { word: "Elon Musk", hint: "Twitter" },
  { word: "Virat Kohli", hint: "Cricket" },
  { word: "MS Dhoni", hint: "Captain Cool" },
  { word: "Neymar", hint: "Brazil" },
  { word: "Kylian Mbappe", hint: "Fast" },
  { word: "Priyanka Chopra", hint: "Global" },

  // ── Sports & Games ────────────────────────────────────
  { word: "Cricket", hint: "Bat & Ball" },
  { word: "Volleyball", hint: "Net" },
  { word: "PUBG Mobile", hint: "Masu bhat" },
  { word: "Free Fire", hint: "Battle Royale" },
  { word: "Ludo", hint: "Dice" },
  { word: "Carom Board", hint: "Strike" },
  { word: "Chess", hint: "King" },
  { word: "Dashain Kite", hint: "String" },
  { word: "Dandi Biyo", hint: "Traditional" },

  // ── School & Everyday Nepal ───────────────────────────
  { word: "SLC Exam", hint: "Iron Gate" },
  { word: "Tuition Class", hint: "Evening" },
  { word: "School Diary", hint: "Homework" },
  { word: "NTC", hint: "Call" },
  { word: "eSewa", hint: "Digital Wallet" },
  { word: "Khalti", hint: "Payment" },
  { word: "IME Remittance", hint: "Send Money" },
  { word: "Guthi", hint: "Community" },
  { word: "Deuda Song", hint: "Cultural" },

  // ── Nature & Animals ──────────────────────────────────
  { word: "One Horned Rhino", hint: "Chitwan" },
  { word: "Snow Leopard", hint: "Himalayas" },
  { word: "Red Panda", hint: "Fluffy" },
  { word: "Yak", hint: "Mountain" },
  { word: "Monsoon", hint: "Flood" },
  { word: "Bagmati River", hint: "Kathmandu" },
  { word: "Pheasant Bird", hint: "Bird" },
  { word: "Rhododendron", hint: "Flower" },

  // ── Tech & Media ──────────────────────────────────────
  { word: "YouTube", hint: "Subscribe" },
  { word: "TikTok", hint: "Short Video" },
  { word: "Facebook", hint: "Like" },
  { word: "Instagram", hint: "Reels" },
];
